hotel/booking/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns=(
    url(r'^$',views.bookingCreate,name='create'),
    url(r'^list/$',views.bookingList,name='list'),
    url(r'^detail/(?P<booking_id>[0-9]+)/$',views.bookingDetail,name='detail'),
    url(r'^edit/(?P<booking_id>[0-9]+)/$',views.BookingEdit.as_view()),
    )

hotel/comments/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns=(
    url(r'^$',views.commentList,name='list'),
    url(r'^review/$',views.commentReview,name='review'),
    url(r'^detail/(?P<comment_id>[0-9]+)/$',views.commentDetail,name='detail'),
    
    )

hotel/hotel_project2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    url(r'',include('myprofile.urls', namespace="myprofile")),
    url(r'comments/',include('comments.urls',namespace='comments')),
    url(r'booking/',include('booking.urls',namespace='booking')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

hotel/myprofile/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns=(
    url(r'^$',views.main,name='main'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^registrate/$',views.registrate,name='registrate'),
    url(r'^profile/$',views.profile,name='profile'), 
    url(r'^imageLoad/$', views.imageLoad, name='imageLoad'),
    url(r'^budget-room/$', views.BudgetView.as_view(), name='budget'),
    url(r'^lux-room/$', views.LuxView.as_view(), name='lux'),
    url(r'^business-room/$', views.BusinessView.as_view(), name='business'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    
    )

hotel/myprofile/models.py
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.db import models


class UserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Email непременно должен быть указан')

        user = self.model(
            email=UserManager.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email=email, password=password)
        user.is_admin=True
        user.is_superuser=True
        user.is_active=True
        user.save(using=self._db)
        return user



class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        'Email адрес',
        unique=True,
        db_index=True,
        max_length=255
        )
    firstname = models.CharField(
        'Имя/Сокращенное название компании',
        max_length=100,
        blank=True
        )
    surname = models.CharField(
        'Фамилия/Полное название компании',
        max_length=150,
        blank=True
        )
    patronymic = models.CharField(
        'Отчество/Название компании на иностранном языке',
        max_length=100,
        blank=True
        )
    CATEGORY_TYPES = (
	('P','Individuals'),
	('L','Legal person'),
    )
    category = models.CharField(
        'Тип лица',
        max_length=1,
        choices=CATEGORY_TYPES,
        default='P'
        )
    STATUS_TYPES = (
        ('U','User'),
	('M','Manager'),
    )
    status = models.CharField(
        'Статус',
        max_length=1,
        choices=STATUS_TYPES,
        default='U'
        )
    is_ban=models.BooleanField(
        'Забанен?',
        default=False
        )
    balance=models.IntegerField(
        'Баланс',
        default=0,
        blank=True
        )
    country=models.CharField(
        'Страна',
        max_length=50,
        blank=True
        )
    city=models.CharField(
        'Город',
        max_length=50,
        blank=True
        )
    phone=models.CharField(
        'Контактный номер',
        max_length=20,
        blank=True
        )
    index=models.IntegerField(
        'Почтовый индекс',
        null=True,
        blank=True
        )
    street=models.CharField(
        'Улица',
        max_length=20,
        blank=True
        )
    home=models.CharField(
        'Номер дома',
        max_length=10,
        blank=True
        )
    region=models.CharField(
        'Область',
        max_length=20,
        blank=True
        )
    office=models.IntegerField(
        'Номер дома/офиса',
        null=True,
        blank=True
        )
    birthday=models.DateField(
        'День рождения',
        null=True,
        blank=True
        )
    dateofreg=models.DateTimeField(
        'date joined',
        auto_now_add=True
        )
    is_admin = models.BooleanField(
        'Суперпользователь',
        default=False
    )
    
    @property
    def is_staff(self):
        return self.is_admin
    
    def __str__(self):
        return self.email

    def get_short_name(self):
        return self.email

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()
	
    class Meta():
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'





class UserAvatar(models.Model):
    user=models.OneToOneField(User)
    avatar=models.ImageField(
        'Аватар',
        upload_to='users/',
        null=True,
        blank=True
        )
    
    def __unicode__(self):
        return unicode(self.picture.name)

hotel/myprofile/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model
from myprofile.models import User,UserAvatar
from django.forms.extras.widgets import SelectDateWidget

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(
        widget=forms.TextInput(attrs={
            'class':'form-control',
            'type':'password',
            'placeholder':'Enter password',
            }),
    )
    password2 = forms.CharField(
        widget=forms.TextInput(attrs={
            'class':'form-control',
            'type':'password',
            'placeholder':'Enter password',
            }),
    )
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Пароль и подтверждение не совпадают')
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['email',]
        widgets = {
            'email': forms.TextInput(attrs={'class':'form-control', 'type':'email', 'placeholder':'Enter email'}),
            }
        
class UserChangeForm(forms.ModelForm):

    '''
    Форма для обновления данных пользователей. Нужна только для того, чтобы не
    видеть постоянных ошибок "Не заполнено поле password" при обновлении данных
    пользователя.
    '''
    password = ReadOnlyPasswordHashField(
        widget=forms.PasswordInput,
        required=False
    )

    def save(self, commit=True):
        user = super(UserChangeForm, self).save(commit=False)
        password = self.cleaned_data["password"]
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['email', ]

class ProfileForm(forms.ModelForm):
  class Meta:
    model = get_user_model()
    fields = ['email','firstname','surname','patronymic','category',
              'balance','country','city','phone',
              'index','street','home','region','office',
              'birthday']
    widgets = {
        'email': forms.TextInput(attrs={'class':'form-control', 'type':'email', 'placeholder':'Enter email'}),
        'firstname': forms.TextInput(attrs={'class':'form-control'}),
        'surname': forms.TextInput(attrs={'class':'form-control'}),
        'patronymic': forms.TextInput(attrs={'class':'form-control'}),
        'category': forms.Select(attrs={'class':'form-control'}),
        'balance': forms.TextInput(attrs={'class':'form-control'}),
        'country': forms.TextInput(attrs={'class':'form-control'}),
        'city': forms.TextInput(attrs={'class':'form-control'}),
        'phone': forms.TextInput(attrs={'class':'form-control'}),
        'index': forms.TextInput(attrs={'class':'form-control'}),
        'street': forms.TextInput(attrs={'class':'form-control'}),
        'home': forms.TextInput(attrs={'class':'form-control'}),
        'region': forms.TextInput(attrs={'class':'form-control'}),
        'office': forms.TextInput(attrs={'class':'form-control'}),
        'birthday': SelectDateWidget(years=range(1901, 2017),attrs={'class':'form-control'}),

        }

class UserAvatarForm(forms.ModelForm):
    class Meta:
        model= UserAvatar
        fields=['avatar']
        widgets = {
            'user': forms.HiddenInput(),
            }

hotel/myprofile/views.py
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from myprofile.models import User,UserAvatar
from comments.models import Comment
from myprofile.forms import UserCreationForm,ProfileForm,UserAvatarForm
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.views.generic.base import TemplateView

def main(request):
    commentsList=Comment.objects.all().order_by('-date')[:3]
    return render(request, 'index.html',{'commentsList':commentsList})

@csrf_protect
def login(request):
    args = {}
    if request.user.is_authenticated():
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = auth.authenticate(email=email, password=password)
        if user is not None:
            auth.login(request, user)
            return HttpResponseRedirect('/')
        else:
            error = 'Email или пароль введены неверно'
            return render(request, 'login.html',{'error':error})

    return render(request, 'login.html', args)

@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

@csrf_protect
def registrate(request):
    args={}
    args['form']=UserCreationForm()
    if request.POST:
        newuser_form=UserCreationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(
                email=newuser_form.cleaned_data['email'],
                password=newuser_form.cleaned_data['password2']
                )
            auth.login(request,newuser)
            return HttpResponseRedirect('/')
        else:
            args['form']=newuser_form
    return render(request,'registrate.html', args)

@csrf_protect
def profile(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login/')
    message = 'Ваш профиль был изменен!'
    error = 'Ошибка при заполнении полей'
    profile=()
    try:
        profile=UserAvatar.objects.get(user_id=request.user.id)
    except:
        pass
    form = ProfileForm(instance = request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance = request.user)
        if form.is_valid():
            form.save()
            return render(request, 'profile.html', {'form': form,'profile':profile,'message': message})
        return render(request, 'profile.html', {'form': form,'profile':profile,'error': error})
    return render(request, 'profile.html', {'form': form,'profile':profile,})

@csrf_protect
def imageLoad(request):
    if request.method == 'POST':
        form = UserAvatarForm(request.POST, request.FILES)
        if form.is_valid():
            preavatar=None
            try:
                preavatar=UserAvatar.objects.get(user_id=request.user.id)
            except:
                pass
            if preavatar is not None:
                preavatar.avatar=form.cleaned_data['avatar']
                preavatar.save()
            else:
                response = form.save(commit=False)
                response.user = request.user
                response.save()
            return render(request, 'imageLoad.html', {
                'form': form
                })
    else:
        form = UserAvatarForm(instance = request.user)
    return render(request, 'imageLoad.html', {
        'form': form
    })

class BudgetView(TemplateView):
    template_name = "budget.html"

class LuxView(TemplateView):
    template_name = "lux.html"

class BusinessView(TemplateView):
    template_name = "business.html"
    
class AboutView(TemplateView):
    template_name = "about.html"

hotel/myprofile/templates/about.html
{% extends "base.html" %}
{% block title %}
Отель "Название" - Профиль
{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
	  <p><a href="{% url 'comments:list' %}">Список коментариев</a></p>
      <p><a href="{% url 'comments:review' %}">Написать коментарий</a></p>
	  <p><a href="{% url 'booking:create' %}">Оформить заявку</a></p>
    </div>
    <div class="col-sm-10 text-left"> 

<div class="jumbotron">
  <h1>Отель "Название"</h1>      
  <p class='text-left'/>Отличный отель, дружелюбный персонал, номера с красивейшими видами из окна
</div>
<div class="container">
<img src="{% static 'hotel.jpg' %}" width="600" height="480" alt="Image">
  <p class='text-left'/><b>Дополнительно:</b> Wi-fi, парковка.  
  <p class='text-left'/><b>Досуг:</b> На территории отеля постоянно проходят мероприятия которые ведут наши лучшие аниматоры  
  <p class='text-left'/><b>Телефон:</b>1 (111) 111-11-11
  <p class='text-left'/><b>Адрес:</b>
</div>
</div>
</div>
</div>
{% endblock %}

hotel/myprofile/templates/budget.html
{% extends "base.html" %}
{% block title %}
Отель "Название" - Профиль
{% endblock %}
{% block content %}
{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
	  <img src="{% static 'budget.jpg' %}" alt="Image">
        <div class="carousel-caption">
          <h3>Бюджетный номер</h3>
          <p><b>1000р за ночь</b></p>
        </div>      
      </div>
<div class="container text-center">  
</div>
      <div class="item">
        <img src="{% static 'budget2.jpg' %}" alt="Image">
        <div class="carousel-caption">
          <h3>Бюджетный номер</h3>
          <p><b>1200р за ночь</b></p>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
<p class='text-left'/><b>Количество спальных мест:</b> 1-2
<p class='text-left'/><b>Дополнительно:</b> Wi-fi и тд.
<br>
<br>
	<div class="container-fluid text-center">
        <a class="btn btn-success btn-lg" href="{% url 'booking:create' %}"> ОФОРМИТЬ ЗАЯВКУ </a> 
    </div>
{% endblock %}

hotel/myprofile/templates/business.html
{% extends "base.html" %}
{% block title %}
Отель "Название" - Профиль
{% endblock %}
{% block content %}
{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
	  <img src="{% static 'business.jpg' %}" alt="Image">
        <div class="carousel-caption">
          <h3>Номер бизнес-класса</h3>
          <p><b>1500р за ночь</b></p>
        </div>      
      </div>
<div class="container text-center">  
</div>
      <div class="item">
        <img src="{% static 'business2.jpg' %}" alt="Image">
        <div class="carousel-caption">
          <h3>Номер бизнес-класса</h3>
          <p><b>1700р за ночь</b></p>
        </div>      
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>
<p class='text-left'/><b>Количество спальных мест:</b> 1-2
<p class='text-left'/><b>Дополнительно:</b> Wi-fi и тд.
<br>
<br>
	<div class="container-fluid text-center">
        <a class="btn btn-success btn-lg" href="{% url 'booking:create' %}"> ОФОРМИТЬ ЗАЯВКУ </a> 
    </div>
{% endblock %}

hotel/myprofile/templates/imageLoad.html
{% extends "base.html" %}
{% block title %}
Отель "Название" - Коментарии
{% endblock %}
{% block content %}
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <p><a href="{% url 'booking:create' %}">Оформить заявку</a></p>
	  <p><a href="{% url 'booking:list' %}">Список заявок</a></p>
	  <p><a href="{% url 'myprofile:profile' %}">Профиль</a></p>
    </div>
    <div class="col-sm-10 text-left"> 
	{% block myprofilePlace %}
	<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
	</form>
	{% endblock %}
    </div>
	
  </div>
</div>
{% endblock %}

hotel/myprofile/templates/index.html
{% extends "roomBase.html" %}
{% block title %}
Отель "Название"
{% endblock %}
{% block content %}
{% load staticfiles %}
<div class="container text-center">    
    <br>
	{% if user.is_authenticated %}
	<div class="container-fluid text-center">
        <a class="btn btn-success btn-lg" href="{% url 'booking:create' %}"> ОФОРМИТЬ ЗАЯВКУ </a> 
    </div>
	{% else %}
    <div class="container-fluid text-center">
        <a class="btn btn-success btn-lg" href="{% url 'myprofile:registrate' %}"> ЗАРЕГИСТРИРУЙТЕСЬ </a> 
    </div>
	{% endif %}
  <h2>Отель</h2>
  <div class="row">
    <div class="col-sm-4">
	<a href="{% url 'myprofile:budget' %}">
      <img src="{% static 'budget.jpg' %}" class="img-responsive" style="width:100%" alt="Image">
      <p>Бюджетный номер</p>
	</a>
    </div>
	<div class="col-sm-4"> 
	<a href="{% url 'myprofile:lux' %}">
      <img src="{% static 'lux.jpg' %}" class="img-responsive" style="width:100%" alt="Image">
      <p>Номер люкс</p> 
    </a>	  
    </div>
    <div class="col-sm-4"> 
	<a href="{% url 'myprofile:business' %}">
      <img src="{% static 'business.jpg' %}" class="img-responsive" style="width:100%" alt="Image">
      <p>номер бизнес-класса</p>  
	</a>
    </div>
	<div class="col-sm-4">
	<h3> Последние отзывы </h3>
	{% for comment in commentsList %}
      <div class="well">
	  <a href="{% url 'comments:detail' comment_id=comment.pk %}">
	  <p>автор: {{ comment.user.surname }} {{ comment.user.firstname }} {{ comment.user.patronymic }}</p>
	  <p>{{comment.title}}</p>
	  </a>
      </div>
	{% endfor %}
    </div>
	</div>
	 </div>

    
  </div>
</div><br>
{% endblock %}

hotel/myprofile/templates/login.html
{% extends "base.html" %}
{% block title %}
Отель "Название" - Аутентификация
{% endblock %}
{% block content %}
<div class="container-fluid text-center">
    <h3>Авторизация</h3>
    <form class="form-horizontal" action="{% url 'myprofile:login' %}" method="POST">
    {% csrf_token %}
	{% if error %}
    <div class="alert alert-danger alert-dismissable fade in">
	    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	    {{ error }}
	</div>
	{% endif %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="email">Email:</label>
        <div class="col-sm-9">
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="password">Password:</label>
        <div class="col-sm-9"> 
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
        </div>
    </div>
    <div class="form-group"> 
        <div class="col-sm col-sm-12">
            <button type="submit" class="btn btn-default">Submit</button>
	        or
	        <a class="btn btn-success" href="{% url 'myprofile:registrate' %}">Sing up</a>
        </div>
    </div>
    </form>
</div>
{% endblock %}

hotel/myprofile/templates/myprofileBase.html
{% extends "base.html" %}
{% block title %}
Отель "Название" - Коментарии
{% endblock %}
{% block content %}
<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <p><a href="{% url 'booking:list' %}">Сисок заявок</a></p>
      <p><a href="{% url 'booking:create' %}">Оформить заявку</a></p>
      <p><a href="{% url 'myprofile:profile' %}">Профиль</a></p>
    </div>
    <div class="col-sm-10 text-left"> 
	{% block myprofilePlace %}
	{% endblock %}
    </div>
  </div>
</div>
{% endblock %}

hotel/myprofile/templates/profile.html
{% extends "myprofileBase.html" %}
{% block title %}
Отель "Название" - Профиль
{% endblock %}
{% block myprofilePlace %}
<div class="container-fluid text-center">
    <h3>Профиль</h3>
	{% if message %}
    <div class="alert alert-success alert-dismissable fade in">
	    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	    {{ message }}
	</div>
	{% endif %}
	{% if error %}
    <div class="alert alert-danger alert-dismissable fade in">
	    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	    {{ error }}
	</div>
	{% endif %}
    <form class="form-horizontal" action="{% url 'myprofile:profile' %}" method="POST">
	{% if profile.avatar != "" %}
	<img src="{{ MEDIA_URL }}{{profile.avatar}}" width="200" height="222">
	{% else %}
	<img src="https://placehold.it/1200x400?text=IMAGE" width="200" height="222">
	{% endif %}
	<p />
	<br /><a class="btn btn-success" href="{% url 'myprofile:imageLoad' %}">Изменить аватар</a>
	<p />
	{% csrf_token %}
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.email.id_for_label }}">Email:</label>
            <div class="col-sm-6">
                {{ form.email }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.firstname.id_for_label }}">Имя/Сокращенное название компании</label>
            <div class="col-sm-9">
                {{ form.firstname }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.surname.id_for_label }}">Фамилия/Полное название компании:</label>
            <div class="col-sm-9">
                {{ form.surname }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.patronymic.id_for_label }}">Отчество/Название компании на иностранном языке:</label>
            <div class="col-sm-9">
                {{ form.patronymic }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.category.id_for_label }}">Тип лица:</label>
            <div class="radio col-sm-9">
                {{ form.category }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.balance.id_for_label }}">Баланс:</label>
            <div class="col-sm-9">
                {{ form.balance }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.country.id_for_label }}">Страна:</label>
            <div class="col-sm-9">
                {{ form.country }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.city.id_for_label }}">Город:</label>
            <div class="col-sm-9">
                {{ form.city }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.phone.id_for_label }}">Телефон:</label>
            <div class="col-sm-9">
                {{ form.phone }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.index.id_for_label }}">Почтовый индекс:</label>
            <div class="col-sm-9">
                {{ form.index }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.street.id_for_label }}">Улица:</label>
            <div class="col-sm-9">
                {{ form.street }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.home.id_for_label }}">Дом:</label>
            <div class="col-sm-9">
                {{ form.home }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.region.id_for_label }}">Область:</label>
            <div class="col-sm-9">
                {{ form.region }}
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.office.id_for_label }}">Номер дома/офиса:</label>
            <div class="col-sm-9">
                {{ form.office }}
            </div>
        </div>
        <div class="form-group">
		<div class='form-inline'>
            <label class="control-label col-sm-2" for="{{ form.birthday.id_for_label }}">День рождения:</label>
            <div class="col-sm-9">
                {{ form.birthday }}
            </div>
		</div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="{{ form.avatar.id_for_label }}">Аватар:</label>
            <div class="col-sm-9">
                {{ form.avatar }}
            </div>
        </div>
		<input type="submit" value="Save" class='btn btn-success  btn-lg'/>
    </form>
</div>
{% endblock %}

hotel/myprofile/templates/registrate.html
{% extends "base.html" %}
{% block title %}
Отель "Название" - Регистрация
{% endblock %}
{% block content %}
<div class="container-fluid text-center">
    <h3>Регистрация</h3>
    <form class="form-horizontal" action="{% url 'myprofile:registrate' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="{{ form.email.id_for_label }}">Email:</label>
        <div class="col-sm-9">
        {{ form.email }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="password1">Password:</label>
        <div class="col-sm-9">
        {{ form.password1 }}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="password2">Password again:</label>
        <div class="col-sm-9">
        {{ form.password2 }}
        </div>
    </div>
	<div class="form-group"> 
        <div class="col-sm col-sm-12">
	        <button type="submit" class="btn btn-default">Submit</button>
        </div>
    </div>
    </form>
</div>
{% endblock %}