hotel/booking/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns=(
    url(r'^$',views.bookingCreate,name='create'),
    url(r'^list/$',views.bookingList,name='list'),
    url(r'^detail/(?P<booking_id>[0-9]+)/$',views.bookingDetail,name='detail'),
    url(r'^edit/(?P<booking_id>[0-9]+)/$',views.BookingEdit.as_view()),
    )

hotel/hotel_project2/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    url(r'',include('myprofile.urls', namespace="myprofile")),
    url(r'comments/',include('comments.urls',namespace='comments')),
    url(r'booking/',include('booking.urls',namespace='booking')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

hotel/myprofile/urls.py
from django.conf.urls import include,url
from . import views

urlpatterns=(
    url(r'^$',views.main,name='main'),
    url(r'^login/$',views.login,name='login'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^registrate/$',views.registrate,name='registrate'),
    url(r'^profile/$',views.profile,name='profile'), 
    url(r'^imageLoad/$', views.imageLoad, name='imageLoad'),
    url(r'^budget-room/$', views.BudgetView.as_view(), name='budget'),
    url(r'^lux-room/$', views.LuxView.as_view(), name='lux'),
    url(r'^business-room/$', views.BusinessView.as_view(), name='business'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    
    )

hotel/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
  <title>{% block title %}Bootstrap Example {% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>
    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    
     html {
     position: relative; 
     min-height: 100%;
    }
  body {
     /* Margin bottom by footer height */
     margin-bottom: 60px;
  }
  footer {
     position: absolute;
     bottom: 0;
     width: 100%;
     /* Set the fixed height of the footer here */
     height: 60px;
     background-color: #f2f2f2;
  }
    
  .carousel-inner img {
      width: 100%; /* Set width to 100% */
      margin: auto;
      min-height:200px;
  }

  /* Hide the carousel text when the screen is less than 600 pixels wide */
  @media (max-width: 600px) {
    .carousel-caption {
      display: none; 
    }
  }
  </style>
</head>
<body>
<!-- Навигационная панель -->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
	<!-- Кнопка вызова меню при max-width: 600px -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="{% url 'myprofile:main' %}">Главная</a>
    </div>
	<!-- Пункты навигационной панели -->
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'myprofile:profile' %}">Профиль</a></li>
        <li><a href="{% url 'comments:list' %}">Отзывы</a></li>
		<li><a href="{% url 'myprofile:about' %}">О нас</a></li>
      </ul>
	  <!-- Кнопка log in -->
	  {% if user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'myprofile:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      </ul>
	  {% else %}
	  <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'myprofile:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
	  {% endif %}
    </div>
  </div>
</nav>
{% block content %}

{% endblock %}
<footer >
<div  class="text-center">
  <br>
  Footer Text
</div>
</footer>

</body>
</html>